# Generated by Django 5.0.6 on 2026-05-19 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programado'), ('LIVE', 'En vivo'), ('FINISHED', 'Finalizado'), ('SUSPENDED', 'Suspendido'), ('VOIDED', 'Anulado')], default='SCHEDULED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('1X2', 'Resultado 1X2')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Abierto a apuestas'), ('SUSPENDED', 'Suspendido temporalmente'), ('SETTLED', 'Liquidado')], default='OPEN', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('LOCAL', 'Gana local'), ('DRAW', 'Empate'), ('AWAY', 'Gana visitante')], max_length=10)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=6)),
                ('won', models.BooleanField(blank=True, default=None, null=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='events.market')),
            ],
        ),
        migrations.AddConstraint(
            model_name='selection',
            constraint=models.UniqueConstraint(fields=('market', 'code'), name='unique_selection_per_market'),
        ),
    ]
