# Generated by Django 5.0.6 on 2026-05-20 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('TEMPORARY_7', 'Temporal 7 días'), ('TEMPORARY_30', 'Temporal 30 días'), ('TEMPORARY_90', 'Temporal 90 días'), ('INDEFINITE', 'Indefinida')], max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_exclusions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'ends_at'], name='compliance__user_id_4d062a_idx')],
            },
        ),
    ]
