# Generated by Django 5.0.6 on 2026-05-20 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('weekly_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('monthly_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('pending_daily', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('pending_daily_at', models.DateTimeField(blank=True, null=True)),
                ('pending_weekly', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('pending_weekly_at', models.DateTimeField(blank=True, null=True)),
                ('pending_monthly', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('pending_monthly_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_limit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
