services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-fairbet_db}
      - POSTGRES_USER=${POSTGRES_USER:-fairbet_admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-fairbet_pass}
    ports:
      - "${POSTGRES_PORT_HOST:-5432}:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT_HOST:-6379}:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local

volumes:
  postgres_data: