# Generated by Django 5.0.6 on 2026-05-20 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, db_index=True, default='', max_length=9)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('kyc_status', models.CharField(choices=[('PENDING_VERIFICATION', 'Pendiente de verificación'), ('VERIFIED', 'Verificado'), ('BLOCKED', 'Bloqueado'), ('SELF_EXCLUDED', 'Autoexcluido')], default='PENDING_VERIFICATION', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
