# Generated by Django 5.0.6 on 2026-05-19 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Validación'), ('ACCEPTED', 'Aceptada Activa'), ('WON', 'Ganada'), ('LOST', 'Perdida'), ('CANCELLED', 'Cancelada')], default='ACCEPTED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lock_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bet', to='wallet.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
